##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [3.7.1] date: [Sun Apr 26 18:14:56 ICT 2020]
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = template


######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -O0


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

######################################
# source
######################################
# C sources
C_SOURCES =  
 C_SOURCES += Src/main.c
 C_SOURCES += Src/stm32f4xx_it.c
 C_SOURCES += Src/system_stm32f4xx.c
 C_SOURCES += Src/delay_lib.c
 C_SOURCES += Src/init_config.c
#C_SOURCES += Drivers/STM32F4xx_StdPeriph_Driver/src/misc.c
#C_SOURCES += Drivers/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_adc.c
#C_SOURCES += Drivers/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_can.c
#C_SOURCES += Drivers/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cec.c
#C_SOURCES += Drivers/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_crc.c
#C_SOURCES += Drivers/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp.c
#C_SOURCES += Drivers/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp_aes.c
#C_SOURCES += Drivers/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp_des.c
#C_SOURCES += Drivers/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp_tdes.c
#C_SOURCES += Drivers/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dac.c
#C_SOURCES += Drivers/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dbgmcu.c
#C_SOURCES += Drivers/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dcmi.c
#C_SOURCES += Drivers/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dfsdm.c
#C_SOURCES += Drivers/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dma.c
#C_SOURCES += Drivers/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dma2d.c
#C_SOURCES += Drivers/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dsi.c
#C_SOURCES += Drivers/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_exti.c
#C_SOURCES += Drivers/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_flash.c
#C_SOURCES += Drivers/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_flash_ramfunc.c
#C_SOURCES += Drivers/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_fmc.c
#C_SOURCES += Drivers/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_fmpi2c.c
#C_SOURCES += Drivers/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_fsmc.c
C_SOURCES += Drivers/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_gpio.c
#C_SOURCES += Drivers/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_hash.c
#C_SOURCES += Drivers/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_hash_md5.c
#C_SOURCES += Drivers/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_hash_sha1.c
#C_SOURCES += Drivers/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_i2c.c
#C_SOURCES += Drivers/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_iwdg.c
#C_SOURCES += Drivers/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_lptim.c
#C_SOURCES += Drivers/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_ltdc.c
#C_SOURCES += Drivers/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_pwr.c
#C_SOURCES += Drivers/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_qspi.c
C_SOURCES += Drivers/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rcc.c
#C_SOURCES += Drivers/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rng.c
#C_SOURCES += Drivers/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rtc.c
#C_SOURCES += Drivers/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_sai.c
#C_SOURCES += Drivers/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_sdio.c
#C_SOURCES += Drivers/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_spdifrx.c
#C_SOURCES += Drivers/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_spi.c
#C_SOURCES += Drivers/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_syscfg.c
C_SOURCES += Drivers/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_tim.c
C_SOURCES += Drivers/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_usart.c
#C_SOURCES += Drivers/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_wwdg.c

# ASM sources
ASM_SOURCES =  \
startup_stm32f411xe.s


#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m4

# fpu
FPU = -mfpu=fpv4-sp-d16

# float-abi
FLOAT-ABI = -mfloat-abi=hard

# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DUSE_STDPERIPH_DRIVER \
-DSTM32F411xE \
-D"HSE_VALUE=25000000"


# AS includes
AS_INCLUDES = 

# C includes
C_INCLUDES =  \
-IInc \
-IDrivers/STM32F4xx_StdPeriph_Driver/inc \
-IDrivers/CMSIS/Device/ST/STM32F4xx/Include \
-IDrivers/CMSIS/Include


# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS = $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = STM32F411XX_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys 
LIBDIR = 
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR) 
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	
	
$(BUILD_DIR):
	mkdir $@		

#######################################
# flash
#######################################
flash: 
	@echo "Flashing $(BUILD_DIR)/$(TARGET).elf with OpenOCD..."
	@openocd -f interface/stlink.cfg -f target/stm32f4x.cfg -c "adapter speed 2000" -c "program $(BUILD_DIR)/$(TARGET).elf reset exit" || echo "Please activate Openocd"

#######################################
# erase
#######################################
erase: 
	@echo "Erasing STM32 flash with OpenOCD..."
	@openocd -f interface/stlink.cfg -f target/stm32f4x.cfg -c "init" -c "reset halt" -c "stm32f4x mass_erase 0" -c "shutdown" || echo "Please activate Openocd"

#######################################
# clean up
#######################################  
clean:
#	rm -fR $(BUILD_DIR)       # For Linux
	-@cmd /c "if exist $(BUILD_DIR) rmdir /S /Q $(BUILD_DIR)"
  
#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# *** EOF ***